name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp'
runs:
    using: 'composite'
    steps:
      - name: "Slack Notification (Unformatted)"
        if: env.SLACKIFY_MARKDOWN != 'true'
        uses: "./"
        env:
          GITHUB_RUN: "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
branding:
  icon: 'bell'
  color: 'yellow'